dependencies:
- role: andrewrothstein.unarchive-deps
  version: v1.1.1
galaxy_info:
  author: Andrew Rothstein
  company: BlackRock
  description: installs etcd and etcdctl
  galaxy_tags:
  - kv
  - raft
  - consensus
  license:
  - MIT
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Alpine
    versions:
    - all
  - name: Debian
    versions:
    - all
